version: 2
registries:
  npm-registry-node-bit-dev:
    type: npm-registry
    url: https://node.bit.dev
    token: '${{secrets.NPM_REGISTRY_NODE_BIT_DEV_TOKEN}}'

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 7
    ignore:
      - dependency-name: cypress
        versions:
          - 6.3.0
          - 6.4.0
          - 6.5.0
          - 6.6.0
          - 6.7.0
          - 6.7.1
          - 6.8.0
          - 7.0.0
          - 7.0.1
          - 7.1.0
      - dependency-name: '@typescript-eslint/eslint-plugin'
        versions:
          - 4.10.0
          - 4.15.2
      - dependency-name: typescript
        versions:
          - 3.9.9
          - 4.2.2
      - dependency-name: start-server-and-test
        versions:
          - 1.12.0
      - dependency-name: eslint-plugin-prettier
        versions:
          - 3.3.1
      - dependency-name: tslib
        versions:
          - 2.0.3
          - 2.1.0
      - dependency-name: gatsby
        versions:
          - 2.32.4
          - 2.32.5
      - dependency-name: '@angular/animations'
        versions:
          - 11.0.5
          - 11.2.1
    registries:
      - npm-registry-node-bit-dev
